-- ================================================================
-- AI CAREER NAVIGATOR - SEED DATABASE (data.sql)
-- 20+ Extensible Career Profiles, Requirements, and Routes
-- ================================================================

INSERT INTO careers (career_code, title, category, description, beginner_difficulty,
    preferred_education_levels, compatible_degrees, related_interests, important_academic_subjects,
    entry_level_roles, advanced_roles, approx_salary_min_lpa, approx_salary_max_lpa, salary_reference_source, active)
VALUES
('software_engineer', 'Software Engineer', 'Software & Cloud',
'Designs, develops, tests, and maintains robust software systems, enterprise backend services, and scalable web applications.',
'Moderate', 'BTech / BE, Degree (BCA / B.Sc CS), Postgraduate (MCA / MTech), Diploma (Lateral)',
'CSE, IT, ECE, BCA, MCA, B.Sc Computer Science',
'Coding, Problem Solving, Web Development, Cloud, Algorithms',
'Mathematics, Computer Science, Data Structures, Algorithms',
'Junior Software Engineer, Associate Developer, Trainee Programmer',
'Senior Software Engineer, Technical Architect, Engineering Manager',
6.0, 24.0, 'India Tech Industry Survey 2024 (Approximate Reference)', true),

('ai_engineer', 'AI & Machine Learning Engineer', 'AI & Data',
'Builds neural networks, machine learning models, predictive pipelines, and generative AI agents that automate complex tasks.',
'Challenging', 'BTech / BE, Postgraduate (MTech / MS / MCA), Degree (B.Sc Data Science / Math)',
'CSE, AI / ML, Data Science, Mathematics, Statistics',
'AI, Mathematics, Data Science, Problem Solving, Research',
'Advanced Mathematics, Calculus, Linear Algebra, Probability, Computer Science',
'Junior ML Engineer, AI Associate, Data Scientist - L1',
'Lead AI Scientist, VP of AI / ML, Principal Research Engineer',
8.5, 36.0, 'India Tech Industry Survey 2024 (Approximate Reference)', true),

('data_scientist', 'Data Scientist', 'AI & Data',
'Transforms vast raw datasets into predictive insights, business intelligence models, and statistical forecasts using machine learning and analytics.',
'Moderate', 'BTech / BE, Degree (B.Sc / BCA / B.Com Analytics), Postgraduate (M.Sc / MBA / MCA)',
'CSE, Data Science, Mathematics, Statistics, Economics',
'Data Science, Mathematics, Business, Problem Solving, Research',
'Statistics, Probability, Linear Algebra, Economics, Python/R',
'Junior Data Scientist, Business Intelligence Associate, Data Analyst',
'Principal Data Scientist, Head of Analytics, Chief Data Officer (CDO)',
7.0, 28.0, 'India Tech Industry Survey 2024 (Approximate Reference)', true),

('data_analyst', 'Data Analyst', 'Business & Analytics',
'Analyzes organizational data using SQL, Excel, and BI dashboards (Power BI / Tableau) to drive data-informed business decisions.',
'Easy', 'Degree (BCA, B.Sc, B.Com, BBA), BTech / BE, Postgraduate',
'BCA, B.Com, BBA, B.Sc, CSE, IT, MBA',
'Mathematics, Business, Data Science, Communication',
'Statistics, Business Mathematics, English',
'Junior Data Analyst, MIS Executive, Reporting Analyst',
'Senior Analytics Consultant, Lead BI Architect, Analytics Director',
4.5, 16.0, 'India Tech Industry Survey 2024 (Approximate Reference)', true),

('cloud_devops_engineer', 'Cloud & DevOps Engineer', 'Software & Cloud',
'Architects resilient cloud infrastructure on AWS/Azure/GCP, automates CI/CD deployment pipelines, and manages containerized microservices.',
'Moderate', 'BTech / BE, Diploma (Lateral), Degree (BCA / B.Sc)',
'CSE, IT, ECE, BCA, MCA',
'Cloud, DevOps, Coding, Electronics, Networking',
'Operating Systems, Computer Networks, Linux, Mathematics',
'Cloud Support Associate, Junior DevOps Engineer, Site Reliability Trainee',
'Cloud Solutions Architect, DevOps Lead, Director of Infrastructure',
7.0, 30.0, 'India Tech Industry Survey 2024 (Approximate Reference)', true),

('cybersecurity_analyst', 'Cybersecurity Analyst', 'Security & Infrastructure',
'Protects corporate networks, clouds, and applications against malicious threats, vulnerabilities, and digital intrusions.',
'Moderate', 'BTech / BE, Degree (BCA / B.Sc CS), Diploma, Postgraduate',
'CSE, IT, Cybersecurity, ECE, BCA, MCA',
'Cybersecurity, Coding, Problem Solving, Networking',
'Computer Networks, Operating Systems, Cryptography, Ethics',
'SOC Analyst - L1, Junior Security Consultant, Penetration Tester Trainee',
'Chief Information Security Officer (CISO), Security Architect, Threat Hunter',
6.5, 26.0, 'India Tech Industry Survey 2024 (Approximate Reference)', true),

('full_stack_developer', 'Full Stack Web Developer', 'Software & Cloud',
'Builds modern, responsive user interfaces and high-performance server-side APIs utilizing frameworks like React, Spring Boot, Node.js, and SQL.',
'Moderate', 'BTech / BE, Degree (BCA, B.Sc CS), Diploma, Postgraduate',
'CSE, IT, BCA, MCA, Any Degree with Bootcamp',
'Web Development, Coding, Design, Creativity, Problem Solving',
'Computer Science, Web Technologies, Database Systems',
'Junior Full Stack Developer, Frontend Associate, Backend Developer',
'Lead Full Stack Architect, Engineering Lead, CTO',
5.5, 22.0, 'India Tech Industry Survey 2024 (Approximate Reference)', true),

('backend_developer', 'Backend Developer', 'Software & Cloud',
'Focuses on core server business logic, microservices, databases, authentication, and high-throughput API integrations.',
'Moderate', 'BTech / BE, Degree (BCA / B.Sc), Postgraduate (MCA / MTech)',
'CSE, IT, BCA, MCA',
'Coding, Problem Solving, Cloud, Databases',
'Object-Oriented Programming, Database Management, Algorithms',
'Junior Java / Python Developer, Backend Associate',
'Principal Backend Engineer, Distributed Systems Architect',
6.0, 25.0, 'India Tech Industry Survey 2024 (Approximate Reference)', true),

('mobile_developer', 'Mobile Application Developer', 'Software & Cloud',
'Creates native and cross-platform mobile apps for Android and iOS using Kotlin, Swift, Flutter, or React Native.',
'Moderate', 'BTech / BE, Degree (BCA / B.Sc), Diploma',
'CSE, IT, BCA, MCA',
'Mobile Development, Coding, Design, Creativity',
'Object-Oriented Design, Mobile Computing, UI Principles',
'Junior Android/iOS Developer, Flutter Trainee',
'Lead Mobile Architect, Head of Mobile Engineering',
5.0, 20.0, 'India Tech Industry Survey 2024 (Approximate Reference)', true),

('ui_ux_designer', 'UI / UX Designer', 'Design & Product',
'Researches user behavior, creates interactive wireframes, prototypes, and crafts accessible design systems in Figma.',
'Easy', 'Any Degree (B.Des, B.Tech, BA, B.Sc, B.Com), 12th Pass with Portfolio',
'Design, Computer Science, Arts, Psychology, Multimedia',
'Design, Creativity, Communication, Problem Solving',
'Visual Arts, Psychology, Human-Computer Interaction',
'Associate UI/UX Designer, Visual Designer, Product Design Intern',
'Principal Product Designer, VP of Design, Creative Director',
5.0, 22.0, 'India Tech Industry Survey 2024 (Approximate Reference)', true),

('game_developer', 'Game Developer & Graphics Programmer', 'Software & Cloud',
'Programs real-time gameplay mechanics, physics engines, shaders, and 3D virtual worlds using Unity, Unreal Engine, and C++ / C#.',
'Challenging', 'BTech / BE, Degree (B.Sc Animation / Game Dev), Diploma',
'CSE, IT, Game Design, Multimedia, Mathematics',
'Gaming, Coding, Creativity, Mathematics, Design',
'Linear Algebra, Trigonometry, 3D Physics, Computer Graphics',
'Junior Game Programmer, Gameplay Scripting Intern',
'Lead Game Architect, Technical Director, Studio Head',
5.0, 24.0, 'India Tech Industry Survey 2024 (Approximate Reference)', true),

('product_manager', 'Tech Product Manager', 'Design & Product',
'Defines product roadmaps, balances user requirements with business metrics, and coordinates engineering, design, and marketing teams.',
'Challenging', 'BTech / BE + MBA, Any Graduate with Tech Experience',
'Engineering, Management, Economics, Computer Applications',
'Leadership, Business, Problem Solving, Communication, Product Development',
'Business Management, Economics, Analytical Thinking',
'Associate Product Manager (APM), Product Analyst',
'Director of Product, VP of Product, Chief Product Officer (CPO)',
9.0, 40.0, 'India Tech Industry Survey 2024 (Approximate Reference)', true),

('embedded_iot_engineer', 'Embedded Systems & IoT Engineer', 'Core Engineering',
'Programs microcontrollers (ARM, ESP32, Arduino) and firmware to bridge physical hardware with cloud networks and sensors.',
'Challenging', 'BTech / BE (ECE, EEE, CSE), Diploma in Electronics',
'ECE, EEE, Mechatronics, Instrumentation, CSE',
'Electronics, Coding, Practical/Hands-on Work, Robotics',
'Digital Electronics, Microprocessors, Signals & Systems, C/C++',
'Graduate Engineer Trainee (GET), Firmware Engineer - L1',
'Principal Embedded Architect, Director of Hardware Engineering',
5.5, 22.0, 'India Tech Industry Survey 2024 (Approximate Reference)', true),

('financial_analyst', 'Financial & Quant Analyst', 'Business & Analytics',
'Models capital markets, builds corporate valuation reports, and performs risk assessments using financial metrics and algorithmic tools.',
'Moderate', 'Degree (B.Com, BBA, Economics, Math), MBA Finance, CA/CFA',
'Commerce, Economics, Finance, Mathematics, Statistics',
'Business, Mathematics, High Salary, Problem Solving',
'Accounting, Corporate Finance, Statistics, Economics',
'Junior Financial Analyst, Research Associate, Equity Research Trainee',
'Portfolio Manager, VP of Investment Banking, CFO',
6.0, 30.0, 'India Tech Industry Survey 2024 (Approximate Reference)', true),

('digital_marketer', 'Digital Marketing & Growth Strategist', 'Business & Analytics',
'Drives customer acquisition through SEO, performance marketing (Google/Meta ads), content strategy, and conversion rate optimization.',
'Easy', 'Any Degree (BBA, B.Com, BA, B.Sc, BCA)',
'Marketing, Business, Mass Media, Arts, Commerce',
'Creativity, Communication, Social Interaction, Business',
'Marketing Fundamentals, English Communication, Basic Analytics',
'Digital Marketing Executive, SEO Specialist, Content Strategist',
'Growth Marketing Director, Chief Marketing Officer (CMO)',
4.0, 18.0, 'India Tech Industry Survey 2024 (Approximate Reference)', true),

('bioinformatics_scientist', 'Bioinformatics & Computational Biologist', 'Healthcare & Life Sciences',
'Applies algorithms, statistical models, and genomics databases to discover drugs, analyze DNA sequences, and advance personalized medicine.',
'Advanced', 'Degree (B.Sc Biotech), BTech (Bioinformatics), Postgraduate (M.Sc/M.Tech/Ph.D)',
'Biotechnology, Bioinformatics, Biology, CSE',
'Biology, Research, Problem Solving, Helping People',
'Biology, Genetics, Biochemistry, Computer Science',
'Junior Bioinformatician, Research Assistant - Genomics',
'Principal Bioinformatics Scientist, Head of Computational Biology',
6.0, 25.0, 'India Tech Industry Survey 2024 (Approximate Reference)', true),

('civil_services_officer', 'Civil Services & Public Administration', 'Civil & Public Services',
'Executes public policy, coordinates governance programs, and serves communities through competitive civil examinations (UPSC / State PSC).',
'Advanced', 'Any Recognized Bachelor Degree (B.Tech, BA, B.Sc, B.Com, MBBS)',
'Any Discipline / Open to all graduates',
'Government Career, Helping People, Leadership, Job Security, Social Interaction',
'Indian Polity, History, Geography, General Studies, Ethics',
'Sub-Divisional Magistrate / Assistant Commissioner, Probationary Officer',
'District Magistrate, Department Secretary, Chief Secretary',
7.0, 18.0, 'Government of India Pay Commission Scale (Reference)', true);
